# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Introduction to Robotics and Perception
author: Frank Dellaert and Seth Hutchinson
logo: logo.png
only_build_toc_files: true
execute_notebooks: on

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/gtbook/robotics  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering: false
  google_analytics_id: UA-312077-7

# add require to support plotly
sphinx:
  config:
    bibtex_reference_style: author_year
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js
    myst_enable_extensions:
    - html_image
    - amsmath
    - dollarmath
    html_theme_options:
      navigation_with_keys: true


