name: gtbook
channels:
  - conda-forge
dependencies:
  - python=3.9
  - conda-lock
  - black
  - jupyter-book>=0.15
  - python-graphviz
  - ipywidgets>=7.5
  - pandas
  - matplotlib=3.5.3
  - pillow # section 5.3 etc..
  - pytorch
  - timm
  - nbformat
  - pip
  - pip:
      - plotly # in pip for binder
      - kaleido # needed for png output
      - gtbook
